models:
  # all of these models have pre-normalized embeddings
  - all-mpnet-base-v2
  - all-MiniLM-L6-v2
  - all-distilroberta-v1
  - multi-qa-distilbert-cos-v1
datasets:
  - "big_patent a"
  - gfissore/arxiv-abstracts-2021
  - "cnn_dailymail 3.0.0"
  - EdinburghNLP/xsum
max_homology_dim: 2
n_components: 3
normalize: False
n_projections:
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
n_samples:
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384