[tool.poetry]
name = "pesto"
version = "0.1.0"
description = "Pairwise Embedding Score using Topological Overlays"
authors = ["jeremy.wayland <jeremy.don.wayland@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.3"
gudhi = "3.8.0"
SciPy = "^1.11.4"
scikit-learn = "^1.4.0"
matplotlib = "^3.8.2"
seaborn = "^0.13.1"
jupyterlab = "^4.0.11"
sentence-transformers = "^2.2.2"
datasets = "^2.16.1"
omegaconf = "^2.3.0"
llm = "^0.12"


[tool.poetry.dev-dependencies]
black = "^23.12.1"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
